run_base_dir: "/content/drive/MyDrive"
# run_base_dir: "."


#  Data

data:
  data_dir:   "data/"
  train_file: "data1_train.csv"   # columns: text | anger | disgust | fear | joy | sadness | surprise
  val_file:   "data1_val.csv"
  test_file:  "data1_test.csv"

  auto_split:  false    # if true, splits train_file into train / val / test automatically
  val_ratio:   0.10
  test_ratio:  0.10

  max_length:  128      # maximum tokenised sequence length (tokens)
  seed:        42
  num_workers: 2        

#  Stage 1 — Binary: Neutral vs Has-Emotion

stage1:
  # Model
  model:
    name:    "electra" #  electra | bert | roberta
    dropout: 0.1
  # Training
  training:
    epochs:                  10
    batch_size:              32
    lr:                      3.0e-5    
    weight_decay:            0.01
    optimizer:               "adamw"
    scheduler:               "cosine_warmup"
    warmup_ratio:            0.10
    early_stopping_patience: 5        
    threshold:               0.5

    # Inference 
    inference_window: 1

    # Loss
    loss:     "bce_weighted"

    # Sampling
    sample: "down"  # down / over
    ratio:    1.0     


#  Stage 2 — Multi-Label: 6 Ekman Emotions

stage2:
  # Model
  model:
    name:    "bert" # bert | roberta | electra
    dropout: 0.2
  # Training
  training:
    epochs:                  20
    batch_size:              32
    lr:                      2.0e-5
    weight_decay:            0.01
    optimizer:               "adamw"
    scheduler:               "cosine_warmup"
    warmup_ratio:            0.10
    early_stopping_patience: 5        
    threshold:               0.5

    # Inference
    inference_window: 1

    # Loss 
    loss: "asymmetric" # bce | bce_weighted | asymmetric 

    # ASL parameters:
    asl_gamma_pos: 0.0
    asl_gamma_neg: 2.0
    asl_clip:      0.05

    # Augmentation 
    augment: true
